const ACTIONS = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_ORDERS: 'SET_ORDERS',
    SET_CART_ITEM: 'SET_CART_ITEM',
    SET_SERVER_CART: 'SET_SERVER_CART',
    SET_CART_ITEM_QTY: 'SET_CART_ITEM_QTY',
    DELETE_CART_ITEM: 'DELETE_CART_ITEM',
    SET_IS_FETCHING: 'SET_IS_FETCHING',
    SET_ONE_PRODUCT: 'SET_ONE_PRODUCT',
    SET_SUBMIT: 'SET_SUBMIT'
}

export default ACTIONS