const ACTIONS = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_CART_ITEM: 'SET_CART_ITEM',
    SET_SERVER_CART: 'SET_SERVER_CART',
    SET_CART_ITEM_QTY: 'SET_CART_ITEM_QTY',
    DELETE_CART_ITEM: 'DELETE_CART_ITEM',
    SET_PAGE: 'SET_PAGE',
    SET_PAGE_QTY: 'SET_PAGE_QTY',
    SET_IS_FETCHING: 'SET_IS_FETCHING',
    SET_ONE_PRODUCT: 'SET_ONE_PRODUCT',
}

export default ACTIONS