const ACTIONS = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_CART: 'SET_CART',
    SET_PAGE: 'SET_PAGE',
    SET_PAGE_QTY: 'SET_PAGE_QTY',
    SET_IS_FETCHING: 'SET_IS_FETCHING',
    SET_ONE_PRODUCT: 'SET_ONE_PRODUCT'
}

export default ACTIONS